negativetwelve/jest-plugins

.eslintrc.yml, circle.yml, package.json, packages/jest-plugin-its/README.md, packages/jest-plugin-its/package.json, packages/jest-plugin-its/src/__tests__/its.spec.js, packages/jest-plugin-its/src/index.js, packages/jest-plugin-its/src/its.js, packages/jest-plugin-its/src/subject.js, packages/jest-plugin-set/package.json, packages/jest-plugins/package.json, yarn.lock
* Adds `jest-plugin-its` to the set of packages.
=> [Plugin] Add jest-plugin-its imported from jest-its

packages/jest-plugin-context/README.md, packages/jest-plugin-context/package.json, packages/jest-plugin-context/setup.js, packages/jest-plugin-context/src/__tests__/context.spec.js, packages/jest-plugin-context/src/context.js
* Adds the `jest-plugin-context` from `jest-context`.
=> [Plugin] Add jest-plugin-context from jest-context

packages/jest-plugin-its/setup.js
=> [jest-plugin-its] Add the jest-plugin-its setup file

README.md, packages/jest-plugin-action/README.md, packages/jest-plugin-action/package.json, packages/jest-plugin-action/setup.js, packages/jest-plugin-action/src/__tests__/action.spec.js, packages/jest-plugin-action/src/action.js
* Adds `jest-plugin-action` package + update README.
=> [Plugin] Add jest-plugin-action + tests + update README

README.md, package.json, packages/jest-plugin-console-matchers/README.md, packages/jest-plugin-console-matchers/package.json, packages/jest-plugin-console-matchers/setup.js, packages/jest-plugin-console-matchers/src/__tests__/matchers.spec.js, packages/jest-plugin-console-matchers/src/matchers.js, packages/jest-plugin-its/package.json
* Adds `jest-plugin-console-matchers` with specs.
=> [Plugin] Add jest-plugin-console-matchers with tests for matchers

README.md, packages/jest-plugin-unhandled-promise/README.md, packages/jest-plugin-unhandled-promise/package.json, packages/jest-plugin-unhandled-promise/setup.js, packages/jest-plugin-unhandled-promise/src/__tests__/install.spec.js, packages/jest-plugin-unhandled-promise/src/install.js
* Adds `jest-plugin-unhandled-promise` + tests + README entry
=> [Plugin] Add jest-plugin-unhandled-promise with tests and README entry

README.md, packages/jest-plugins-recommended/README.md, packages/jest-plugins-recommended/__tests__/plugin.spec.js, packages/jest-plugins-recommended/package.json, packages/jest-plugins-recommended/setup.js
=> [Plugins] Create jest-plugins-recommended with sane defaults

packages/jest-plugin-action/package.json, packages/jest-plugin-console-matchers/package.json, packages/jest-plugin-context/package.json, packages/jest-plugin-its/package.json, packages/jest-plugin-set/package.json, packages/jest-plugin-unhandled-promise/package.json, packages/jest-plugins/package.json
=> [Meta] Update the repository fields to point to jest-plugins

packages/jest-plugins-rspec/README.md, packages/jest-plugins-rspec/__tests__/plugin.spec.js, packages/jest-plugins-rspec/package.json, packages/jest-plugins-rspec/setup.js
=> [Plugin] Add jest-plugins-rspec and group all plugins with rspec syntax

.babelrc, package.json, packages/jest-plugins-recommended/package.json, packages/jest-plugins-recommended/setup.js, yarn.lock
=> [Plugin] Recommended plugins should use rspec set

circle.yml, package.json, yarn.lock
=> [Meta] Add test coverage and upload to coveralls

.travis.yml, README.md
=> [Meta] Add .travis.yml configuration

.eslintignore, README.md, appveyor.yml, package.json, packages/jest-plugin-unhandled-promise/src/__tests__/install.spec.js, yarn.lock
=> [Meta] Update jest to 21 and add appveyor config to run the CI

examples/basic/package.json, examples/basic/src/models/User.js, examples/basic/src/models/__tests__/User.spec.js, packages/jest-plugin-console-matchers/package.json, packages/jest-plugin-console-matchers/setup.js
=> [Plugin] Remove dependency on jest-matchers

packages/jest-plugin-action/src/__tests__/action.spec.js, packages/jest-plugin-console-matchers/src/__tests__/matchers.spec.js, packages/jest-plugin-context/src/__tests__/context.spec.js, packages/jest-plugin-for-each/README.md, packages/jest-plugin-for-each/package.json, packages/jest-plugin-for-each/setup.js, packages/jest-plugin-for-each/src/__tests__/forEach.spec.js, packages/jest-plugin-for-each/src/forEach.js, packages/jest-plugin-its/src/__tests__/its.spec.js, packages/jest-plugin-set/src/__tests__/set.spec.js
=> [Plugin] Create jest-plugin-for-each (replaces with-test-cases)

README.md, package.json, packages/jest-plugins-recommended/__tests__/plugin.spec.js, packages/jest-plugins-recommended/package.json, packages/jest-plugins-recommended/setup.js, yarn.lock
=> [Plugins] Add jest-plugin-for-each to jest-plugins-recommended

packages/jest-plugin-clock/README.md, packages/jest-plugin-clock/package.json, packages/jest-plugin-clock/setup.js, packages/jest-plugin-clock/src/__tests__/clock.spec.js, packages/jest-plugin-clock/src/clock.js, yarn.lock
=> [Plugin] Create jest-plugin-clock with tests

packages/jest-plugin-clock/README.md, packages/jest-plugins-recommended/__tests__/plugin.spec.js, packages/jest-plugins-recommended/package.json, packages/jest-plugins-recommended/setup.js
=> [Plugins] Add jest-plugin-clock to the recommended plugins

package.json, packages/jest-plugin-it-renders/README.md, packages/jest-plugin-it-renders/package.json, packages/jest-plugin-it-renders/setup.js, packages/jest-plugin-it-renders/src/__tests__/__snapshots__/itRenders.spec.js.snap, packages/jest-plugin-it-renders/src/__tests__/itRenders.spec.js, packages/jest-plugin-it-renders/src/itRenders.js, yarn.lock
=> [Plugin] Create jest-plugin-it-renders with tests (and snapshot tests)

packages/jest-plugins-react/README.md, packages/jest-plugins-react/__tests__/__snapshots__/plugins.spec.js.snap, packages/jest-plugins-react/__tests__/plugins.spec.js, packages/jest-plugins-react/package.json, packages/jest-plugins-react/setup.js, packages/jest-plugins-recommended/__tests__/plugins.spec.js, packages/jest-plugins-rspec/__tests__/plugins.spec.js
=> [Plugin] Create jest-plugins-react as a plugins set

packages/jest-plugin-it-renders/README.md, packages/jest-plugin-it-renders/package.json, yarn.lock
=> [Plugin:it-renders] Update react-test-renderer to 16.0.0-beta.5

packages/jest-plugins/src/install.js
=> [jest-plugins] Print the full error when we're unable to require a jest-plugin

packages/jest-plugin-fs/README.md, packages/jest-plugin-fs/package.json, packages/jest-plugin-fs/setup.js, packages/jest-plugin-fs/src/__tests__/fs.spec.js, packages/jest-plugin-fs/src/fs.js, yarn.lock
=> [Plugin] Create jest-plugin-fs to mock the filesystem with tests

packages/jest-plugin-fs/setup.js, packages/jest-plugin-fs/src/__tests__/fs.spec.js, packages/jest-plugin-fs/src/fs.js, packages/jest-plugins-recommended/__tests__/plugins.spec.js, packages/jest-plugins-recommended/package.json, packages/jest-plugins-recommended/setup.js
=> [Plugin] Add jest-plugin-fs to the recommended plugins set

package.json, packages/jest-plugin-it-renders/README.md, packages/jest-plugin-it-shallow-renders/README.md, packages/jest-plugin-it-shallow-renders/package.json, packages/jest-plugin-it-shallow-renders/setup.js, packages/jest-plugin-it-shallow-renders/src/__tests__/__snapshots__/itRenders.spec.js.snap, packages/jest-plugin-it-shallow-renders/src/__tests__/__snapshots__/itShallowRenders.spec.js.snap, packages/jest-plugin-it-shallow-renders/src/__tests__/itShallowRenders.spec.js, packages/jest-plugin-it-shallow-renders/src/itShallowRenders.js, yarn.lock
=> [Plugin] Add jest-plugin-it-shallow-renders support for react components with snapshot tests

packages/jest-plugins-react/__tests__/__snapshots__/plugins.spec.js.snap, packages/jest-plugins-react/__tests__/plugins.spec.js, packages/jest-plugins-react/package.json, packages/jest-plugins-react/setup.js
=> [React] Add jest-plugin-it-shallow-renders to the react plugins set

circle.yml, package.json, yarn.lock
=> [CI] Update yarn, add eslint-plugin-jest + remove -- from commands

packages/jest-plugin-fs/README.md, packages/jest-plugin-fs/mock.js, packages/jest-plugin-fs/package.json, packages/jest-plugin-fs/setup.js, packages/jest-plugin-fs/src/__tests__/fs.spec.js, packages/jest-plugin-fs/src/fs.js
=> [jest-plugin-fs] Add the jest-plugin-fs/mock export for usage within jest

packages/jest-plugin-fs/src/__tests__/fs.spec.js, packages/jest-plugin-fs/src/fs.js
=> [jest-plugin-fs] Add ability to nest files and directories with a test case to validate it

packages/jest-plugin-fs/package.json, packages/jest-plugin-fs/setup.js, packages/jest-plugin-fs/src/__tests__/fs.spec.js, packages/jest-plugin-fs/src/fs.js, yarn.lock
=> [jest-plugin-fs] Add in-memory filesystem as a layer on top of the real one (for the mock)

packages/jest-plugin-fs/src/fs.js
=> [jest-plugin-fs] Do not reset the filesystem when we call mock multiple times

packages/jest-plugin-fs/src/__fixtures__/test.txt, packages/jest-plugin-fs/src/__tests__/fs.spec.js, packages/jest-plugin-fs/src/fs.js
=> [jest-plugin-fs] Add the unmock feature which allows you to read files natively within tests

appveyor.yml, packages/jest-plugin-action/package.json, packages/jest-plugin-clock/package.json, packages/jest-plugin-console-matchers/package.json, packages/jest-plugin-context/package.json, packages/jest-plugin-for-each/package.json, packages/jest-plugin-fs/package.json, packages/jest-plugin-it-renders/package.json, packages/jest-plugin-it-shallow-renders/package.json, packages/jest-plugin-its/package.json, packages/jest-plugin-set/package.json, packages/jest-plugin-unhandled-promise/package.json
Fix #81 
Thanks for the suggestion @peterjuras!
=> [meta] Remove jest-plugins as a peerDependency from individual packages

packages/jest-plugin-it-renders/package.json, packages/jest-plugin-it-shallow-renders/package.json, packages/jest-plugins-react/package.json
=> [jest-plugins-react] Remove peerDependency on react from all react plugins
